global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 1m

scrape_configs:
 - job_name: 'prometheus'
   static_configs:
     - targets: ['prometheus:9090']

 - job_name: 'otel-collector'
   static_configs:
      - targets:
          - otel-collector:8888
          - otel-collector:8889

 # - job_name: 'open_telemetry_product_svc'
 #   static_configs:
 #     - targets:
 #         - open_telemetry_product_svc:80

 # - job_name: 'open_telemetry_pricing_svc'
 #   static_configs:
 #     - targets:
 #         - open_telemetry_pricing_svc:80

rule_files:
  - "rule/alerts.yml"
  - "rule/recording_rule.yml"

alerting:
  alertmanagers:
    - scheme: http
      basic_auth:
        username: "admin"
        password: "password"
      static_configs:
        - targets:
            - localhost:9093






 #Commenting out the job_name 'open_telemetry_product_svc' and 'open_telemetry_pricing_svc' configurations